# Generated by Django 2.2.5 on 2019-10-14 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('image', models.ImageField(upload_to='pictures')),
            ],
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('status', models.CharField(blank=True, choices=[('R', 'Reserved'), ('A', 'Available')], default='A', max_length=1)),
                ('type', models.CharField(blank=True, choices=[('1', '5 Players'), ('2', '7 Players'), ('3', '11 Players')], default='1', max_length=1)),
                ('price', models.CharField(max_length=75)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sport.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_date', models.DateField(null=True)),
                ('schedule_time', models.TimeField(null=True)),
                ('company_reserve', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sport.Company')),
                ('customer_reserve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_reserve', to='user.Customer')),
                ('field_reserve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sport.Field')),
            ],
        ),
    ]
