# Generated by Django 2.2.5 on 2019-11-08 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0002_auto_20191106_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='price',
            field=models.FloatField(null=True),
        ),
    ]
