# Generated by Django 2.2.5 on 2019-10-31 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0004_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
