# Generated by Django 2.2.6 on 2019-11-11 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0005_auto_20191110_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
    ]
