# Generated by Django 2.2.5 on 2019-10-31 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0005_schedule_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='company_reserve',
        ),
    ]
