# Generated by Django 2.2.6 on 2019-11-11 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0006_auto_20191110_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='start_time',
            field=models.TimeField(null=True),
        ),
    ]
