# Generated by Django 2.2.5 on 2019-11-05 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0006_remove_reservation_company_reserve'),
    ]

    operations = [
        migrations.CreateModel(
            name='Implement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('price', models.FloatField(max_length=15)),
                ('add', models.BooleanField()),
            ],
        ),
        migrations.AlterField(
            model_name='company',
            name='town',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='user.Town'),
        ),
        migrations.AlterField(
            model_name='field',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='sport.Company'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='sport.Field'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='implement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sport.Implement'),
        ),
    ]
