# Generated by Django 2.2.5 on 2019-11-05 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0007_auto_20191104_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='implement',
            name='image',
            field=models.ImageField(null=True, upload_to='pictures'),
        ),
    ]
