# Generated by Django 2.2.6 on 2019-11-11 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0009_auto_20191110_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='total',
            field=models.FloatField(null=True),
        ),
    ]
